#$Id: adminedit.inc.pl.ja.pod,v 1.337 2011/12/31 13:06:10 papu Exp $

__END__
=encoding euc-jp

=head1 NAME

adminedit.inc.pl - PyukiWiki 管理者向けプラグイン

=head1 概要

 ?cmd=adminedit&mypage=ページ名

=head1 説明

指定したページを編集・凍結する

編集・凍結するには、凍結パスワードが必要です。

ページ名はエンコードされていなければならない。

=head1 参考

=over 4

=over 4

=item PyukiWiki/Plugin/Admin/adminedit

L<http://pyukiwiki.sfjp.jp/PyukiWiki/Plugin/Admin/adminedit/>

=item PyukiWiki CVS

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/plugin/adminedit.inc.pl?view=log>

=back

=head1 著者

=over 4

=item Nekyo

L<http://nekyo.qp.land.to/>

=item PyukiWiki Developers Team

L<http://pyukiwiki.sfjp.jp/>

=back

=head1 ライセンス

Copyright (C) 2004-2012 by Nekyo.

Copyright (C) 2005-2012 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 2 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
