#$Id: aname.inc.pl.ja.pod,v 1.466 2012/03/01 10:39:21 papu Exp $

__END__
=encoding euc-jp

=head1 NAME

aname.inc.pl - PyukiWiki プラグイン

=head1 概要

 &aname(anchor name);
 #aname(anchor name);

=head1 説明

指定した位置にアンカー(リンクの飛び先)を設定します。

=head1 参考

=item PyukiWiki/Plugin/Standard/aname

L<http://pyukiwiki.sfjp.jp/PyukiWiki/Plugin/Standard/aname/>

=item PyukiWiki CVS

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/plugin/aname.inc.pl?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel-UTF8/plugin/aname.inc.pl?view=log>

=back

=head1 著者

=over 4

=item Nekyo

L<http://nekyo.qp.land.to/>

=item PyukiWiki Developers Team

L<http://pyukiwiki.sfjp.jp/>

=back

=head1 ライセンス

Copyright (C) 2004-2012 by Nekyo.

Copyright (C) 2005-2012 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 3 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
