#$Id: attach.inc.pl.ja.pod,v 1.78 2011/02/22 20:59:12 papu Exp $

__END__
=encoding euc-jp

=head1 NAME

attach.inc.pl - PyukiWiki プラグイン

=head1 概要

 #attach

=head1 説明

ページ上に添付ファイルのアップロードフォームを生成します。また、全体的な添付ファイルの管理を行ないます。

=head1 設定

=head2 pyukiwiki.ini.cgi

=over 4

=item $::file_uploads

添付を 0:使わない/1:使う/2:認証付き/3:削除のみ認証付

=item $::max_filesize

アップロードファイルの最大容量 

=back

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/attach

L<http://pyukiwiki.sourceforge.jp/PyukiWiki/Plugin/Standard/attach/>

=item PyukiWiki CVS

L<http://sourceforge.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/plugin/attach.inc.pl?view=log>

=back

=head1 著者

=over 4

=item Nekyo

L<http://nekyo.qp.land.to/>

=item PyukiWiki Developers Team

L<http://pyukiwiki.sourceforge.jp/>

=back

=head1 ライセンス

Copyright (C) 2004-2011 by Nekyo.

Copyright (C) 2005-2011 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 2 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
