#$Id: color.pl.ja.pod,v 1.82 2011/05/03 20:43:28 papu Exp $

__END__
=encoding euc-jp

=head1 NAME

color.pl - PyukiWiki / YukiWiki プラグイン

=head1 概要

 &color(color, [background-color]){text};
 &color(red){赤で表示};
 &color(#ff0000,#000000){文字赤、背景黒で表示};

=head1 説明

引数で指定したインライン要素の、文字色・背景色を指定します。

このプラグインはYukiWikiと互換性があります。

=head1 補足

旧バージョンの color.inc.pl は廃止しますので、最新の color.pl をダウンロードして、削除する様にして下さい。

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/color

L<http://pyukiwiki.sourceforge.jp/PyukiWiki/Plugin/Standard/color/>

=item PyukiWiki CVS

L<http://sourceforge.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/plugin/color.pl?view=log>

=back

=head1 著者

=over 4

=item Nekyo

L<http://nekyo.qp.land.to/>

=item PyukiWiki Developers Team

L<http://pyukiwiki.sourceforge.jp/>

=back

=head1 ライセンス

Copyright (C) 2004-2011 by Nekyo.

Copyright (C) 2005-2011 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 2 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
