#$Id: listfrozen.inc.pl.ja.pod,v 1.40 2006/03/17 14:00:10 papu Exp $

__END__
=encoding euc-jp

=head1 NAME

listfrozen.inc.pl - PyukiWiki 管理者向けプラグイン

=head1 概要

 ?cmd=listfrozen

=head1 説明

すべてのページのリストを表示し、一覧形式でページの凍結・凍結解除を一度に行ないます。

=head1 参考

=over 4

=item PyukiWiki/Plugin/Admin/listfrozen

L<http://pyukiwiki.sourceforge.jp/PyukiWiki/Plugin/Admin/listfrozen/>

=item PyukiWiki CVS

L<http://cvs.sourceforge.jp/cgi-bin/viewcvs.cgi/pyukiwiki/PyukiWiki-Devel/plugin/listfrozen.inc.pl>

=back

=head1 著者

=over 4

=item Nekyo

L<http://nekyo.hp.infoseek.co.jp/>

=item PyukiWiki Developers Team

L<http://pyukiwiki.sourceforge.jp/>

=back

=head1 ライセンス

Copyright (C) 2004-2006 by Nekyo.

Copyright (C) 2005-2006 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 2 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
