#$Id: location.inc.pl.ja.pod,v 1.259 2011/12/31 13:06:10 papu Exp $

__END__
=encoding euc-jp

=head1 NAME

location.inc.pl - PyukiWiki プラグイン

=head1 概要

 #location(url or ページ名)

=head1 説明

指定したURLまたはページ名に自動移動します。
なお、安全の為に凍結されたページからしか使えません。

=head1 使用方法

 #location(url または ページ名)

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/location

L<http://pyukiwiki.sfjp.jp/PyukiWiki/Plugin/Standard/location/>

=item PyukiWiki CVS

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/plugin/location.inc.pl?view=log>

=back

=head1 著者

=over 4

=item ななみ

L<http://nanakochi.daiba.cx/> etc...

=item PyukiWiki Developers Team

L<http://pyukiwiki.sfjp.jp/>

=back

=head1 ライセンス

Copyright (C) 2005-2012 by ななみ.

Copyright (C) 2005-2012 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 2 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
