#$Id: mailform.inc.pl.ja.pod,v 1.289 2011/12/31 13:06:11 papu Exp $

__END__
=encoding euc-jp

=head1 NAME

mailform.inc.pl - PyukiWiki プラグイン

=head1 概要

 #mailform

=head1 説明

Display Mail form and send to admin mail message.

=head1 使用方法

 #mailform

=head1 著者

=over 4

=item ななみ

L<http://nanakochi.daiba.cx/> etc...

=item PyukiWiki Developers Team

L<http://pyukiwiki.sfjp.jp/>

=back

=head1 ライセンス

Copyright (C) 2005-2012 by ななみ.

Copyright (C) 2005-2012 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 2 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
