#$Id: sbookmark.inc.pl.ja.pod,v 1.372 2012/01/31 10:11:58 papu Exp $

__END__
=encoding euc-jp

=head1 NAME

sbookmark.inc.pl - PyukiWiki プラグイン


=head1 著者

=over 4

=item Nekyo

L<http://nekyo.qp.land.to/>

=item PyukiWiki Developers Team

L<http://pyukiwiki.sfjp.jp/>

=back

=head1 ライセンス

Copyright (C) 2004-2012 by Nekyo.

Copyright (C) 2005-2012 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 3 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
