#$Id: sitemap.inc.pl.ja.pod,v 1.491 2012/03/18 11:23:51 papu Exp $

__END__
=encoding euc-jp

=head1 NAME

sitemap.inc.pl - PyukiWiki プラグイン

=head1 概要

 ?cmd=sitemap

=head1 説明

「明示的」訪問者をナビゲーションしやすくするプラグインです。

=head1 USAGE

=head2 MenuBar

MenuBarでは以下のように記述する

 ***項目名
 [[WikiName]]
 [[ページ]]

(WikiNameだけでは動きません)

=head2 各ページ

MenuBarに登録されたページでは、以下のように記述する

 -[[WikiName]] (WikiNameだけでは動きません)
 -[[ページ]]~
 --[[ページ]]~
 ---[[ページ]]~
 -[[?cmd=プラグイン&.....]]~

 [[リンク>http://www.yahoo.co.jp/]] 等外部リンクははじきます。

=back

=head1 設定

=head2 pyukiwiki.ini.cgi

=over 4

=item $::use_SiteMap

1 にすると、サイトマップを使用します。

=back

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/sitemap

L<http://pyukiwiki.sfjp.jp/PyukiWiki/Plugin/Standard/sitemap/>

=item PyukiWiki CVS

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/plugin/sitemap.inc.pl?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel-UTF8/plugin/sitemap.inc.pl?view=log>

=back

=head1 著者

=over 4

=item Nekyo

L<http://nekyo.qp.land.to/>

=item PyukiWiki Developers Team

L<http://pyukiwiki.sfjp.jp/>

=back

=head1 ライセンス

Copyright (C) 2004-2012 by Nekyo.

Copyright (C) 2005-2012 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 3 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
