#$Id: topicpath.inc.pl.ja.pod,v 1.50 2011/01/25 03:11:15 papu Exp $

__END__
=encoding euc-jp

=head1 NAME

topicpath.inc.pl - PyukiWiki 管理者向けプラグイン

=head1 概要

 コンパクト版以外は自動で読み込まれます。
 または、:Header 等のページにて &topicpath; と記述
 または、スキンファイルに以下を記述
  require 'plugin/topicpath.inc.pl';
  &plugin_topicpath_inline;

=head1 説明

いわゆる「パンくずリスト」です。

ページ名を　/(スラッシュ)区切りで階層表示してそれぞれのページへリンクします。

=head1 参考

=over 4

=item PyukiWiki/Plugin/Admin/topicpath

L<http://pyukiwiki.sourceforge.jp/PyukiWiki/Plugin/Admin/topicpath/>

=item PyukiWiki CVS

L<http://sourceforge.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/plugin/topicpath.inc.pl?view=log>

=item サイト制作/PyukiWiki/プラグイン/パンくずリスト

0.1.5までの対応版です。

L<http://www.re-birth.com/pyuki/wiki.cgi?%a5%b5%a5%a4%a5%c8%c0%a9%ba%ee%2fPyukiWiki%2f%a5%d7%a5%e9%a5%b0%a5%a4%a5%f3%2f%a5%d1%a5%f3%a4%af%a4%ba%a5%ea%a5%b9%a5%c8>

=back

=head1 著者

=over 4

=item Junichi

L<http://www.re-birth.com/>

=item PyukiWiki Developers Team

L<http://pyukiwiki.sourceforge.jp/>

=back

=head1 ライセンス

Copyright (C) 2005-2011 by Junichi.

Copyright (C) 2005-2011 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 2 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
