#$Id: punyurl.inc.pl.ja.pod,v 1.253 2012/01/31 10:12:02 papu Exp $

__END__
=encoding utf-8

=head1 NAME

punyurl.inc.pl - PyukiWiki プラグイン

=head1 概要

ASCII文字以外のドメイン名を持つURLをpunycode形式に変換する

=head1 説明

多言語文字等のASCII文字以外のドメイン名を持つURLをpunycode形式に変換します。

http://日本語.jp/ → http://xn--wgv71a119e.jp/

=head1 警告

perl 5.8.1 以降の環境でないと使用できません。

現在のバージョンは日本語ドメインにしか対応していません。

=head1 使用方法

punyurl.inc.cgi にリネームして下さい。

=head1 上書きする関数

関数 make_link_url を上書きします。

=head1 参考

=over 4

=item PyukiWiki/Plugin/ExPlugin/punyurl

L<http://pyukiwiki.sfjp.jp/PyukiWiki/Plugin/ExPlugin/punyurl/>


=item PyukiWiki CVSレボジトリ

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/lib/punyurl.inc.pl?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel-UTF8/lib/punyurl.inc.pl?view=log>

=back

=head1 著者

=over 4



=item PyukiWiki Developers Team

L<http://pyukiwiki.sfjp.jp/>

=back

=head1 ライセンス

Copyright (C) 2005-2012 by ななみ.

Copyright (C) 2005-2012 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 3 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
