#$Id: iecompatiblehack.inc.pl.ja.pod,v 1.266 2011/12/31 13:06:09 papu Exp $

__END__
=encoding euc-jp

=head1 NAME

iecompatiblehack.inc.pl - PyukiWiki プラグイン

=head1 概要

IEの互換表示ボタンを強制的になくすプラグイン

=head1 説明

Internet Explorere 8 以降で互換表示ボタンが表示されるのを阻止します。

なお、他のコンテンツやスキンのCSSの互換が悪い場合には使用しないで下さい。
ブラウジングできるようにします。

=head1 使用方法

iecompatiblehack.inc.cgi にリネームして下さい。

=head1 上書きする関数

なし

=head1 参考

=over 4

=item PyukiWiki/Plugin/ExPlugin/iecompatiblehack

L<http://pyukiwiki.sfjp.jp/PyukiWiki/Plugin/ExPlugin/iecompatiblehack/>


=item PyukiWiki CVSレボジトリ

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/lib/iecompatiblehack.inc.pl?view=log>

=back

=head1 著者

=over 4



=item PyukiWiki Developers Team

L<http://pyukiwiki.sfjp.jp/>

=back

=head1 ライセンス

Copyright (C) 2005-2012 by ななみ.

Copyright (C) 2005-2012 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 2 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
