#$Id: admin.inc.pl.ja.pod,v 1.253 2012/01/31 10:12:03 papu Exp $

__END__
=encoding utf-8

=head1 NAME

admin.inc.pl - PyukiWiki 管理者向けプラグイン

=head1 概要

 ?cmd=admin

=head1 説明

管理プラグインの実行を支援するメニューを表示する。

=head1 参考

=over 4

=over 4

=item PyukiWiki/Plugin/Admin/admin

L<http://pyukiwiki.sfjp.jp/PyukiWiki/Plugin/Admin/admin/>

=item PyukiWiki CVS

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/plugin/admin.inc.pl?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel-UTF8/plugin/admin.inc.pl?view=log>

=back

=head1 著者

=over 4

=item ななみ

L<http://nanakochi.daiba.cx/> etc...

=item PyukiWiki Developers Team

L<http://pyukiwiki.sfjp.jp/>

=back

=head1 ライセンス

Copyright (C) 2005-2012 by ななみ.

Copyright (C) 2005-2012 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 3 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
