#$Id: img.inc.pl.ja.pod,v 1.331 2012/03/18 11:23:57 papu Exp $

__END__
=encoding utf-8

=head1 NAME

img.inc.pl - PyukiWiki プラグイン

=head1 概要

 #img(http://example.com/image.png)
 #img(http://example.com/image.jpg,right)
 #img(http://example.com/image.gif,l,AlternateText)
 #img(http://example.com/image.gif,center,AlternateText)
 #img(,c)

=head1 説明

画像を表示します。

=head1 使用方法

 #img(image_url,[alt],[l|left],[r|right],center,c)

=over 4

=item image_url

画像のあるURLを指定します。

=item left または l

左寄せします。

=item right または r

右寄せします。

=item center

センタリングします。

=item c

テキストの回りこみを解除します。

=back

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/img

L<http://pyukiwiki.sfjp.jp/PyukiWiki/Plugin/Standard/img/>

=item PyukiWiki CVS

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/plugin/img.inc.pl?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel-UTF8/plugin/img.inc.pl?view=log>

=back

=head1 著者

=over 4

=item Nekyo

L<http://nekyo.qp.land.to/>

=item PyukiWiki Developers Team

L<http://pyukiwiki.sfjp.jp/>

=back

=head1 ライセンス

Copyright (C) 2004-2012 by Nekyo.

Copyright (C) 2005-2012 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 3 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
