#$Id: logs_viewer.inc.pl.ja.pod,v 1.3 2012/01/31 10:12:04 papu Exp $

__END__
=encoding utf-8

=head1 NAME

logs_viewer.inc.pl - PyukiWiki 管理者向けプラグイン

=head1 概要

アクセスログ解析プラグイン（評価版）

=head1 説明

wikiのアクセスログを解析します。

ただし、現状におきましては、未完成です。

動作しない訳ではありませんが、動作環境を満たしていても、古いperlのバージョンですと、正常に集計動作ができない場合があります。

=head1 機能について

このアクセスログ解析プラグインは、生ログを取得する為に開発されたもので、効率的なアクセスログ解析を行えません。

その為、可能であれば、外部のアクセス解析サービスを効率的に利用することをお勧めします。

google analytics は、無料（解析数により課金）で、非常に多くの情報を得ることができ、かつ、PyukiWikiでは拡張プラグインとしてインストールできますので、設置がとても容易です。場合によっては、多くの有料アクセス解析よりも、圧倒的、かつ、効率的な情報を得ることができます。

L<http://pyukiwiki.sfjp.jp/PyukiWiki/Plugin/ExPlugin/google_analytics/>

他にも、他社の無料アクセス解析がありますが、日本国内ですと、これも非常に解析能力、及び、アクセスに対するレスポンスが瞬時に反応できるものとして、Ａｃｅ─ａｎａｌｙｚｅｒ があります。

このアクセス解析プログラムは、広告がついてしまいますので、個人サイトには有効です。


L<http://www.ace-analyzer.com/>

PyukiWiki開発者に寄付するには、こちらから（登録・解析タグ設置で収入になります）

L<http://px.a8.net/svt/ejp?a8mat=1ZIHDM+3K0CGY+2HB0+639IR>

アクセス解析タグを設置するには、adプラグインが便利です。

L<http://pyukiwiki.sfjp.jp/PyukiWiki/Plugin/Nanami/ad/>

=head1 参考

=over 4

=item PyukiWiki/Plugin/Admin/logs_viewer

L<http://pyukiwiki.sfjp.jp/PyukiWiki/Plugin/Admin/logs_viewer>

=item PyukiWiki/Plugin/ExPlugin/logs

L<http://pyukiwiki.sfjp.jp/PyukiWiki/Plugin/ExPlugin/logs/>

=item PyukiWiki CVSレボジトリ

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/lib/Nana/Logs.pml?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel-UTF8/lib/Nana/Logs.pml?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/plugin/logs_viewer.inc.pl?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel-UTF8/plugin/logs_viewer.inc.pl?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/lib/Nana/Logs.pm?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel-UTF8/lib/Nana/Logs.pm?view=log>

このアクセス解析プラグインは、AWStatsから流用し、かつ、改良をした定義を使用しています。

L<http://awstats.sf.net/>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/lib/AWS/browsers.pm?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel-UTF8/lib/AWS/browsers.pm?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/lib/AWS/domains.pm?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel-UTF8/lib/AWS/domains.pm?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/lib/AWS/operating_systems.pm?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel-UTF8/lib/AWS/operating_systems.pm?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/lib/AWS/robots.pm?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel-UTF8/lib/AWS/robots.pm?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/lib/AWS/search_engines.pm?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel-UTF8/lib/AWS/search_engines.pm?view=log>

=back

=head1 著者

=over 4



=item PyukiWiki Developers Team

L<http://pyukiwiki.sfjp.jp/>

=back

=head1 ライセンス

Copyright (C) 2005-2012 by ななみ.

Copyright (C) 2005-2012 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 3 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
