#$Id: twitter.inc.pl.ja.pod,v 1.304 2012/03/01 10:39:26 papu Exp $

__END__
=encoding utf-8

=head1 名前

twitter.inc.pl - PyukiWiki プラグイン

=head1 概要

#twitter(ユーザー名 または #ハッシュタグ[, ヘッダーに表示する文字])

=head1 説明

ツイッターのユーザーのツィート　及び、ツイッターのハッシュタグを表示します。

=head1 注意

同じページに２つ以上設置することはできません。

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/twitter

L<http://pyukiwiki.sfjp.jp/PyukiWiki/Plugin/Standard/twitter/>

=item PyukiWiki CVS

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel/plugin/twitter.inc.pl?view=log>

L<http://sfjp.jp/cvs/view/pyukiwiki/PyukiWiki-Devel-UTF8/plugin/twitter.inc.pl?view=log>

=item twitstat.us

L<http://twitstat.us/>

=back

=head1 著者

=over 4

=item ななみ

L<http://nanakochi.daiba.cx/> etc...

=item PyukiWiki Developers Team

L<http://pyukiwiki.sfjp.jp/>

=back

=head1 ライセンス

Copyright (C) 2005-2012 by ななみ.

Copyright (C) 2005-2012 by PyukiWiki Developers Team

License is GNU GENERAL PUBLIC LICENSE 3 and/or Artistic 1 or each later version.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
